package enums;

public enum Categorie {
    Art,
    Science,
    Fiction,
    peinture,
    drama,
    roman,
    histoire,
    scienceFiction,
    sciencePolitique,
    scienceEconomique,
    scienceMedicale,
    scienceTechnique,
    scienceMathematique,
    scienceInformatique,
    theatre,
    poesie,
    essai,
    biographie,
    memoire,
    journal,
    recueil,
    conte,
    nouvelle,
    feuilleton,
    romanPolicier,
    romanHistorique,
    romanDAmour,
    romanDeScienceFiction,
    romanDeGuerre
}
